Feature: new assets REG, REG Vote Power,  RWA realtime price, Settings updates
RealToken-Community/dashboard-v2 pull request #91
Opened 2024-11-05 18:14 UTC by BenoistP

- Prices for RWA & REG are fetched from Honeyswap (UniV2) pools (average of 2 pools: asset/USDC and asset/wXDAI)
- Filter 'other' assets (i.e. others than RealTokens) in views using a switch (Others assets) in settings
- domain static.debank.com is used for diplaying REG image
next.config.js
- small fix when address has no corresponding user ('User not found' error)
src/components/assetsView/AssetsViewSearch.tsx
- Misc updates in Setting menu
  - 'titles' for sections : Realtime, Theme
  - icons in switches
- Labels optional icon
- Interfaces RWARealtoken, REGRealtoken, REGVotingPowertoken are the same thing as OtherRealtoken (previously named RWARealtoken)
- ABIs
  - ERC20: Full abi
  - UniswapV2FactoryABI
- Consts: tokens & factory addresses, decimals, default prices
consts/otherTokens.ts

2024-11-07 09:58 UTC, jycssu-com commented
Everythings seems good to me, i just added a check for fetching other assets balances only if the addressList is not empty for avoid a double request on app initialization

Despite this, there are still a large number of RPC requests going out, but it seems to be related to the RPC initialization mechanism to look for a working one, so out of the scope of this PR (maybe we need another PR to improve this part)

@NandyBa I'll let you review it on your side too, and approve if everything is good for you (I can't since I committed)

2024-11-19 02:44 UTC, NandyBa requested changes

2024-11-19 02:44 UTC, NandyBa commented on src/hooks/useREG.ts
> +  const averagePrice = averageValues([regPriceUsdc, regPriceWxdai])
Please use `xDAIUSD` and `USDCUSD` price. You can found an example in `PropertityCard`

2024-11-19 02:44 UTC, NandyBa commented on src/utils/blockchain/contract.ts
> +}
Maybe better to define a batch number per query with a default value.
Idea to reduce batch size per attend is good

2024-11-19 13:27 UTC, BenoistP commented on src/hooks/useREG.ts
> +  const averagePrice = averageValues([regPriceUsdc, regPriceWxdai])
Is there a source for USDC price ?
I was looking at
[/home/dev/git/RealToken-Community/dashboard-v2/src/store/features/currencies/currenciesSelector.ts](https://github.com/RealToken-Community/dashboard-v2/blob/d23c1d46f97211ae5bfcb28bbf68973d203f31f0/src/store/features/currencies/currenciesSelector.ts#L4)

https://github.com/RealToken-Community/dashboard-v2/blob/d23c1d46f97211ae5bfcb28bbf68973d203f31f0/src/store/features/currencies/currenciesSlice.ts#L4

but couldn't find one, only XDAI price

2024-11-19 13:42 UTC, BenoistP commented on src/utils/blockchain/contract.ts
> +}
What do you mean by "batch number" ?
Batch query is starting with a size of 100 queries per batch call (second call is 100/2 = 50, third 100/3=33, ...), 
`const MAX_BATCH_CONTRACT_PER_CHUNK = 100`
If there is 555 calls to process it'll split like this
- first attempt: 100, 100, 100, 100, 100, 55
- second attempt: 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,  50, 5
- third: 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 27
- 4: 25 (x 22) , 5
- 5: 20 (x 27) , 15

2024-11-20 10:19 UTC, NandyBa commented on src/utils/blockchain/contract.ts
> +}
I mean a batch size per query

2024-11-20 10:20 UTC, NandyBa commented on src/utils/blockchain/contract.ts
> +}
function1 -> batch size 100
function2 -> batch size 125
function3 -> batch size undefined -> 100
function4 -> batch size 30

2024-11-22 10:47 UTC, BenoistP commented on src/utils/blockchain/contract.ts
> +}
just pushed batch size parameters for customs calls 🫡

2024-11-22 10:48 UTC, BenoistP commented on src/hooks/useREG.ts
> +  const averagePrice = averageValues([regPriceUsdc, regPriceWxdai])
still can't find a source for USDC price 🤔

2024-11-27 14:37 UTC, BenoistP commented on src/hooks/useREG.ts
> +  const averagePrice = averageValues([regPriceUsdc, regPriceWxdai])
Still no answer to my questions.
There's nothing related t prices to be found in src/components/cards/main/PropertiesCard.tsx as far as I can understand.

2024-11-29 19:40 UTC, NandyBa commented on src/hooks/useREG.ts
> +  const averagePrice = averageValues([regPriceUsdc, regPriceWxdai])
Sorry I miss, I was thinking that the were `xdaiusd` and `usdcusd` but there is only xdaiusd in src/repositories/currencies.repository.ts

2024-11-29 19:42 UTC, NandyBa commented on src/hooks/useREG.ts
> +  const averagePrice = averageValues([regPriceUsdc, regPriceWxdai])
Address for usdcusd pricess feed is 0x26C31ac71010aF62E6B486D1132E266D6298857D and come from https://data.chain.link/feeds/xdai/mainnet/usdc-usd

2024-11-29 20:48 UTC, BenoistP commented on src/hooks/useREG.ts
> +  const averagePrice = averageValues([regPriceUsdc, regPriceWxdai])
Ok, thanks, I'll check it

2024-12-04 16:21 UTC, BenoistP commented
- I've added a test for checking providers ability to handle concurrent requests:
(On ETH https://rpc.ankr.com/eth and https://eth-pokt.nodies.app currently fail to resolve balances when "too much" requests are sent)
- Smol fix: getAddressesLockedBalances was fetching vault balances on Eth
- Added 2 additionnal providers for each chain
- Assets prices are now converted from USDC/XDAI to USD before being displayed in user choosen currency
- Additionnal parameters on batchCallOneContractOneFunctionMultipleParams for fine tuning calls (batch sizes, attempts)

2024-12-06 18:16 UTC, BenoistP commented
Hooks calls are duplicated in 2 components (SummaryCard and AssetsView) so the same requests are made when fetching data.
Moving it to index solves it, let me know if it's considered "dirty" i'll revert the last commit.

2024-12-12 00:29 UTC, NandyBa requested changes

2024-12-12 00:29 UTC, NandyBa commented on src/components/assetsView/filters/AssetsViewSort.tsx
> +          (a.rentedUnits ?? 0) / (a.totalUnits ?? 0)
Warning potential divison by zero

2024-12-12 00:42 UTC, NandyBa commented on src/utils/blockchain/regVault.ts
> +}
I think it can be improve but let do that on an other PR

2024-12-12 16:04 UTC, BenoistP commented on src/utils/blockchain/regVault.ts
> +}
Thanks, I've planned to enhance things in coming weeks

2024-12-12 17:41 UTC, BenoistP commented on src/components/assetsView/filters/AssetsViewSort.tsx
> +          (a.rentedUnits ?? 0) / (a.totalUnits ?? 0)
Fix: in case asset.totalUnits is unknown/zero (should not happen)
Divide by ONE instead of ZERO

2024-12-13 02:00 UTC, NandyBa reviewed
When loading the dashboard locally I got 18 properties instead of 20. And when I try a search of RWA on the search bar I don't have it.

2024-12-13 19:02 UTC, NandyBa reviewed
Still present
<img width="1504" alt="Capture d’écran 2024-12-13 à 02 50 52" src="https://github.com/user-attachments/assets/eb2bc8e

Normal comportment: <img width="1507" alt="Capture d’écran 2024-12-13 à 20 01 51" src="https://github.com/user-attachments/assets/2b8d6dbd-fe9f-4dc9-96c3-41e38f4b6990" />
c-cd15-43d2-9e4b-1982ac12e38a" />

Config: no option enabled

2024-12-13 23:16 UTC, BenoistP commented
Should be fixed now, translated paging labels at the same time

2024-12-14 16:07 UTC, NandyBa requested changes

2024-12-14 16:07 UTC, NandyBa commented on src/i18next/locales/en/common.json
> +    "future": "Future",
Please to not change. Do not really correspond to the purpose of the mode

2024-12-14 16:12 UTC, NandyBa commented on src/repositories/RpcProvider.ts
> +}
This part slow down the page loading

2024-12-14 16:12 UTC, NandyBa commented on src/repositories/RpcProvider.ts
> +}
I recommend to run it appart from the front

2024-12-14 16:34 UTC, BenoistP commented on src/i18next/locales/en/common.json
> +    "future": "Future",
right, done

2024-12-15 21:48 UTC, Sigri44 commented
@NandyBa Where are we now? Are there any requests that don't concern the original PR, if I understand correctly?

2024-12-15 21:55 UTC, NandyBa commented
> @NandyBa Where are we now? Are there any requests that don't concern the original PR, if I understand correctly?
???
Currently all is good expect: https://github.com/RealToken-Community/dashboard-v2/pull/91#discussion_r1885109100

2024-12-15 21:59 UTC, BenoistP commented on src/repositories/RpcProvider.ts
> +}
I'll see if i can improve things but if these tests aren't run then there's no garantee next batchs requests will succeed and nothing will be loaded if the rpc can't support multiple requests at the same time (like https://rpc.ankr.com/eth seems like not supporting it)

2024-12-15 22:18 UTC, NandyBa commented on src/repositories/RpcProvider.ts
> +}
Can we populate the code with test results and run tests only for new RPCs, instead of running all tests every time? I don’t want to block the PR, but I think merging it like this is manageable in the develop branch. However, it might create blockers later when escalating to preprod and prod.

2024-12-17 17:44 UTC, BenoistP commented on src/repositories/RpcProvider.ts
> +}
Checks for testing rpc ability to handle batch requests only run once for each rpc, one after the other like it is already the case.
Currently rpc connection checks take around 700ms, additionnal batch check requires 100-150 ms more.
If the first rpcs fails to respond and to handle batch request, the second is tested and so on.

2024-12-17 18:26 UTC, NandyBa approved these changes
Approved. We will revisit the RPC test if we find it annoying

2024-12-17 18:27 UTC, merged